name: "godot-ci export"
on:
  push:
    tags:
      - "v*.*.*"

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: OpenRomu_SDK
  BUILD_PATH_ROOT: /tmp/build
  WIN_BUILD_FOLDER: win_x86-64
  WIN_BUILD_NAME: win_x86-64
  LINUX_BUILD_FOLDER: linux_x86-64
  LINUX_BUILD_NAME: linux_x86-64
  MACOS_BUILD_FOLDER: macOS_x86-64
  MACOS_BUILD_NAME: macOS_x86-64
  WAD3_CLI_REPO: https://github.com/Stalker2106x/wad3-cli/releases/download/v1.0.0/wad3-cli

jobs:
  export-game:
    name: All Platform Export
    runs-on: ubuntu-20.04
    container:
      image: stalker2106x/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Windows build
      - name: Windows Build
        run: |
          mkdir -p ~/.config/godot/
          echo "[gd_resource type=\"EditorSettings\" load_steps=1 format=3]" > ~/.config/godot/editor_settings-4.3.tres
          echo "[resource]" >> ~/.config/godot/editor_settings-4.3.tres
          echo "export/windows/rcedit = \"/opt/rcedit-x86.exe\"" >> ~/.config/godot/editor_settings-4.3.tres
          mkdir -p "${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}"
          cd SDK
          godot --headless --export-release "Windows Desktop" "${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}/${{env.EXPORT_NAME}}.exe"
          mkdir -p "${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}/utils"
          wget $WAD3_CLI_REPO-$WIN_BUILD_NAME.exe -O "${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}/utils/wad3-cli.exe"
          cp -R ../OpenRomu "${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}"
          cd "${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}" && zip -r "${{env.EXPORT_NAME}}-${{github.ref_name}}-${{env.WIN_BUILD_NAME}}.zip" "."
      # Linux build
      - name: Linux Build
        run: |
          mkdir -p "${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}"
          cd SDK
          godot --headless --export-release "Linux" "${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}/${{env.EXPORT_NAME}}.x86_64"
          mkdir -p "${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}/utils"
          wget $WAD3_CLI_REPO-$LINUX_BUILD_NAME -O "${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}/utils/wad3-cli"
          cp -R ../OpenRomu/* "${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}"
          cd "${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}" && zip -r "${{env.EXPORT_NAME}}-${{github.ref_name}}-${{env.LINUX_BUILD_NAME}}.zip" "."
      # Release to this repo
      - name: Private Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}/${{env.EXPORT_NAME}}-${{github.ref_name}}-${{env.WIN_BUILD_NAME}}.zip
            ${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}/${{env.EXPORT_NAME}}-${{github.ref_name}}-${{env.LINUX_BUILD_NAME}}.zip
            ${{env.BUILD_PATH_ROOT}}/${{env.MACOS_BUILD_FOLDER}}/${{env.EXPORT_NAME}}-${{github.ref_name}}-${{env.MACOS_BUILD_NAME}}.zip