name: "godot-ci export"
on:
  push:
    tags:
      - "v*.*.*"

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: OpenRomu_SDK
  BUILD_PATH_ROOT: /tmp/build
  WIN_BUILD_FOLDER: win_x86-64
  WIN_BUILD_NAME: win_x86-64
  LINUX_BUILD_FOLDER: linux_x86-64
  LINUX_BUILD_NAME: linux_x86-64
  MACOS_BUILD_FOLDER: macOS_x86-64
  MACOS_BUILD_NAME: macOS_x86-64

jobs:
  export-game:
    name: All Platform Export
    runs-on: ubuntu-20.04
    container:
      image: stalker2106x/godot-ci:4.3-mono
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Windows build
      - name: Windows Build
        run: |
          mkdir -p ~/.config/godot/
          echo "[gd_resource type=\"EditorSettings\" load_steps=1 format=3]" > ~/.config/godot/editor_settings-4.3.tres
          echo "[resource]" >> ~/.config/godot/editor_settings-4.3.tres
          echo "export/windows/rcedit = \"/opt/rcedit-x86.exe\"" >> ~/.config/godot/editor_settings-4.3.tres
          mkdir -p "${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}"
          godot --headless --export-release "Windows Desktop" "${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}/${{env.EXPORT_NAME}}.exe"
          mkdir -p "${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}/maps"
          cp maps/*.pak "${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}/maps"
          cd "${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}" && zip -r "${{env.EXPORT_NAME}}-${{github.ref_name}}-${{env.WIN_BUILD_NAME}}.zip" "."
      # Linux build
      - name: Linux Build
        run: |
          mkdir -p "${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}"
          godot --headless --export-release "Linux/X11" "${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}/${{env.EXPORT_NAME}}.x86_64"
          mkdir -p "${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}/maps"
          cp maps/*.pak "${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}/maps"
          cd "${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}" && zip -r "${{env.EXPORT_NAME}}-${{github.ref_name}}-${{env.LINUX_BUILD_NAME}}.zip" "."
      # MacOS build
      - name: MacOS Build
        run: |
          mkdir -p "${{env.BUILD_PATH_ROOT}}/${{env.MACOS_BUILD_FOLDER}}"
          godot --headless --export-release "macOS" "${{env.BUILD_PATH_ROOT}}/${{env.MACOS_BUILD_FOLDER}}/${{env.EXPORT_NAME}}-${{github.ref_name}}-${{env.MACOS_BUILD_NAME}}.zip"
      # Release to this repo
      - name: Private Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{env.BUILD_PATH_ROOT}}/${{env.WIN_BUILD_FOLDER}}/${{env.EXPORT_NAME}}-${{github.ref_name}}-${{env.WIN_BUILD_NAME}}.zip
            ${{env.BUILD_PATH_ROOT}}/${{env.LINUX_BUILD_FOLDER}}/${{env.EXPORT_NAME}}-${{github.ref_name}}-${{env.LINUX_BUILD_NAME}}.zip
            ${{env.BUILD_PATH_ROOT}}/${{env.MACOS_BUILD_FOLDER}}/${{env.EXPORT_NAME}}-${{github.ref_name}}-${{env.MACOS_BUILD_NAME}}.zip